In [133]:
using LinearAlgebra
using Printf

function PageRank(websites)
    
    # important variables
    len = length(websites)  # number of websites
    e = vec(ones(len, 1))   # vectors with 1s
    a = vec(zeros(len, 1))  # vector with 1, will edit
    alpha = 0.9            # teleportation constant
    
    # zeros(m, n) creates m x n matrix full of 0s
    # M is square with length of number of websites
    M = zeros(len, len)
    
    # go through each website
    for j in eachindex(websites)
        # go through each link in website
        links = websites[j];
        for i in links
            # there is a link!
            # length(j) = number of links website j has
            M[i,j] = 1 / length(links)
            # others left as 0 since no link
        end
    end
    
    
    # for i in x:y loops from int x to int y with step of 1
    for i in 1:len
        # count(x->x==y, A) returns number of y's in A
        if(count(x->x==0, M[:,i])) == len
            # dangling node since col all 0s!
            a[i] = 1
        end 
    end
    
    S = M + 1/len * e * transpose(a)
    
    # alpha = 0.85, teleport 15% chance
    G = alpha * S + (1 - alpha) * 1/len * e * transpose(e) 
    
    
#     # N(G - 1I) is eigenvector with eigenvalue 1
#     # I dimensions auto scales to G
#     N = nullspace(G - I)
    
#     # if any entry negative, then all entries negative
#     for i in N
#         if i < 0
#             N = -N # makes N positive
#             break
#         end
#     end
    
#     # turn from one col matrix into vector
#     # so we can use delete function later
#     N = vec(N)
    
#     original = copy(N)
#     println("Rankings:")
#     counter = 1 # for printing rankings
#     while !isempty(N)
#         # findmax return 2-tuple: (value, index)
#         a,b = findmax(N)
#         web_num = findall(x->x==a, original)[1]
#         print(counter, ". Website ", web_num)
#         @printf ", (Pagerank = %.6f%s" a ")"
#         println()
#         # remove the max value to find next biggest in next loop
#         deleteat!(N, b)
#         counter += 1
#     end
    
    epsilon = 1
    pi = 1/len * e
    while epsilon > 10^-8
        pi_next = G * pi
        epsilon = norm(pi_next - pi)
        pi = pi_next
    end
    
    original = copy(pi)
    println("Rankings:")
    counter = 1 # for printing rankings
    while !isempty(pi)
        # findmax return 2-tuple: (value, index)
        a,b = findmax(pi)
        web_num = findall(x->x==a, original)[1]
        original[web_num] = 0
        print(counter, ". Website ", web_num)
        @printf ", (Pagerank = %.5f%s" a ")"
        println()
        # remove the max value to find next biggest in next loop
        deleteat!(pi, b)
        counter += 1
    end
    
    return G
    
end


PageRank (generic function with 2 methods)

In [134]:
# websites = Array[[2,3,4],[4,5],[4],[2,3],[1,2,3,4]]
websites = Array[[2,3,4],[3,4],[4],[1,2,3]]
# book = [[2,3],[],[1,2,5],[5,6],[4,6],[4]]

4-element Vector{Array}:
 [2, 3, 4]
 [3, 4]
 [4]
 [1, 2, 3]

In [135]:
G = PageRank(websites)

Rankings:
1. Website 4, (Pagerank = 0.39697)
2. Website 3, (Pagerank = 0.27161)
3. Website 2, (Pagerank = 0.18732)
4. Website 1, (Pagerank = 0.14409)


4×4 Matrix{Float64}:
 0.025  0.025  0.025  0.325
 0.325  0.025  0.025  0.325
 0.325  0.475  0.025  0.325
 0.325  0.475  0.925  0.025

In [126]:
n = vec(nullspace(G - I))
total = 0
for t in eachindex(n)
    total += n[t]
end
n = n / total

5-element Vector{Float64}:
 0.04768930353655891
 0.229030158385767
 0.22903015838576693
 0.37118680841831186
 0.12306357127359517

In [145]:
using LinearAlgebra

function PageRank(websites, links)
    
    # important variables
    len = length(websites)  # number of websites
    e = vec(ones(len, 1))   # vectors with 1s
    a = vec(zeros(len, 1))  # vector with 1, will edit
    alpha = 0.85            # teleportation constant
    
    # zeros(m, n) creates m x n matrix full of 0s
    # M is square with length of number of websites
    M = zeros(len, len)
    
    # go through each pair of links
    # links has 2 columns
    # each row represents a page in col 1 that links to page in col 2
    for j in eachindex(links[:,1])
        # go through each link in website
        web_from = links[j,1]
        web_to = parse(Int32, links[j,2])
        # link from web_from to web_to
        M[web_to, web_from] = 1 / count(x->x==web_from, links[:,1])
    end
    
    
    # for i in x:y loops from int x to int y with step of 1
    for i in 1:len
        # count(x->x==y, A) returns number of y's in A
        if(count(x->x==0, M[:,i])) == len
            # dangling node since col all 0s!
            a[i] = 1
        end 
    end
    
    S = M + 1/len * e * transpose(a)
    
    # alpha = 0.85, teleport 15% chance
    G = alpha * S + (1 - alpha) * 1/len * e * transpose(e) 
    
    epsilon = 1
    pi = 1/len * e
    while epsilon > 10^-8
        pi_next = G * pi
        epsilon = norm(pi_next - pi)
        pi = pi_next
    end
    
    original = copy(pi)
    println("Rankings:")
    counter = 1 # for printing rankings
    while !isempty(pi)
        # findmax return 2-tuple: (value, index)
        a,b = findmax(pi)
        web_num = findall(x->x==a, original)[1]
        original[web_num] = 0
        print(counter, ". Website ", web_num)
        @printf ", (Pagerank = %.5f%s" a ")"
        println()
        println("      ", webpages[web_num])
        # remove the max value to find next biggest in next loop
        deleteat!(pi, b)
        counter += 1
        if counter == 11
            break
        end
    end
    
    return G
    
end


PageRank (generic function with 2 methods)

In [79]:
web = Array[[2,3],[1,3,4],[2,4],[]]

4-element Vector{Array}:
 [2, 3]
 [1, 3, 4]
 [2, 4]
 Any[]

In [80]:
S = PageRank(web)

Rankings:
1. Website 4
2. Website 2
3. Website 3
4. Website 1


4×4 Matrix{Float64}:
 0.0375  0.320833  0.0375  0.25
 0.4625  0.0375    0.4625  0.25
 0.4625  0.320833  0.0375  0.25
 0.0375  0.320833  0.4625  0.25

In [84]:
nullspace(S - I)

4×1 Matrix{Float64}:
 -0.3510967079597246
 -0.5555421448836748
 -0.5003128088426081
 -0.5637296517178335

In [524]:
a,b = findmax(vec(N))

(-0.25175440748900685, 1)

In [498]:
N[b]

10.0

In [512]:
v = [1 2 3 4]
v = vec(v)

4-element Vector{Int64}:
 1
 2
 3
 4

In [513]:
deleteat!(v, 2)

3-element Vector{Int64}:
 1
 3
 4

In [39]:
r = vec([1 2 2 4])

4-element Vector{Int64}:
 1
 2
 2
 4

In [40]:
findall(x->x==1, r)

1-element Vector{Int64}:
 1

In [41]:
r[3]=3

3

In [47]:
vec(ones(5, 1)) * transpose(vec(ones(5,1)))

5×5 Matrix{Float64}:
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0

In [36]:
r = vec(zeros(5, 1))

5-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0

In [551]:
r

4-element Vector{Int64}:
 10
  2
  2
  4

In [552]:
R

4-element Vector{Int64}:
 1
 2
 2
 4

In [11]:
H = [1/60 1/6 19/60 1/60 1/60 1/60 ; 
 7/15 1/6 19/60 1/60 1/60 1/60 ; 
 7/15 1/6 1/60 1/60 1/60 1/60 ; 
 1/60 1/6 1/60 1/60 7/15 11/12 ; 
 1/60 1/6 19/60 7/15 1/60 1/60 ; 
 1/60 1/6 1/60 7/15 7/15 1/60]

6×6 Matrix{Float64}:
 0.0166667  0.166667  0.316667   0.0166667  0.0166667  0.0166667
 0.466667   0.166667  0.316667   0.0166667  0.0166667  0.0166667
 0.466667   0.166667  0.0166667  0.0166667  0.0166667  0.0166667
 0.0166667  0.166667  0.0166667  0.0166667  0.466667   0.916667
 0.0166667  0.166667  0.316667   0.466667   0.0166667  0.0166667
 0.0166667  0.166667  0.0166667  0.466667   0.466667   0.0166667

In [12]:
H^50

6×6 Matrix{Float64}:
 0.037212   0.037212   0.037212   0.037212   0.037212   0.037212
 0.0539573  0.0539573  0.0539573  0.0539573  0.0539573  0.0539573
 0.0415057  0.0415057  0.0415057  0.0415057  0.0415057  0.0415057
 0.375081   0.375081   0.375081   0.375081   0.375081   0.375081
 0.205998   0.205998   0.205998   0.205998   0.205998   0.205998
 0.286246   0.286246   0.286246   0.286246   0.286246   0.286246

In [15]:
using CSV
using DataFrames

In [16]:
df = DataFrame(CSV.File("hollins.csv"))

┌ Warning: thread = 1 warning: parsed expected 2 columns, but didn't reach end of line around data row: 2433. Parsing extra columns and widening final columnset
└ @ CSV /Users/lucaszheng/.julia/packages/CSV/9LsxT/src/file.jl:635
┌ Warning: thread = 1 warning: only found 2 / 4 columns around data row: 2434. Filling remaining columns with `missing`
└ @ CSV /Users/lucaszheng/.julia/packages/CSV/9LsxT/src/file.jl:634
┌ Warning: thread = 1 warning: only found 2 / 4 columns around data row: 2435. Filling remaining columns with `missing`
└ @ CSV /Users/lucaszheng/.julia/packages/CSV/9LsxT/src/file.jl:634
┌ Warning: thread = 1 warning: only found 2 / 4 columns around data row: 2436. Filling remaining columns with `missing`
└ @ CSV /Users/lucaszheng/.julia/packages/CSV/9LsxT/src/file.jl:634
┌ Warning: thread = 1 warning: only found 2 / 4 columns around data row: 2437. Filling remaining columns with `missing`
└ @ CSV /Users/lucaszheng/.julia/packages/CSV/9LsxT/src/file.jl:634
┌ Warning: thread =

29887×4 DataFrame
   Row │ 6012   23875                              Column3    Column4   
       │ Int64  String                             String31?  String31? 
───────┼────────────────────────────────────────────────────────────────
     1 │     1  http://www1.hollins.edu/           missing    missing   
     2 │     2  http://www.hollins.edu/            missing    missing   
     3 │     3  http://www1.hollins.edu/Docs/Com…  missing    missing   
     4 │     4  http://www1.hollins.edu/Docs/For…  missing    missing   
     5 │     5  http://www1.hollins.edu/Docs/mis…  missing    missing   
     6 │     6  http://www1.hollins.edu/Docs/GVC…  missing    missing   
     7 │     7  http://www1.hollins.edu/docs/eve…  missing    missing   
     8 │     8  http://www1.hollins.edu/docs/com…  missing    missing   
     9 │     9  http://www1.hollins.edu/Docs/Aca…  missing    missing   
    10 │    10  http://www1.hollins.edu/Docs/Com…  missing    missing   
    11 │    11  http://www1.hollins.edu/Docs/com…  missing    missing   
   ⋮   │   ⋮                    ⋮                      ⋮          ⋮
 29878 │  6005  6004                               missing    missing   
 29879 │  5955  6005                               missing    missing   
 29880 │  6004  6005                               missing    missing   
 29881 │  6002  6006                               missing    missing   
 29882 │  6002  6007                               missing    missing   
 29883 │  6002  6008                               missing    missing   
 29884 │  6002  6009                               missing    missing   
 29885 │  6002  6010                               missing    missing   
 29886 │  6002  6011                               missing    missing   
 29887 │  6005  6012                               missing    missing   
                                                      29866 rows omitted

In [139]:
webpages = df[1:6012, 2]

6012-element Vector{String}:
 "http://www1.hollins.edu/"
 "http://www.hollins.edu/"
 "http://www1.hollins.edu/Docs/CompTech/Network/webmail_faq.htm"
 "http://www1.hollins.edu/Docs/Forms/GetForms.htm"
 "http://www1.hollins.edu/Docs/misc/travel.htm"
 "http://www1.hollins.edu/Docs/GVCalendar/gvmain.htm"
 "http://www1.hollins.edu/docs/events/events.htm"
 "http://www1.hollins.edu/docs/comptech/mainviruses.htm"
 "http://www1.hollins.edu/Docs/Academics/acad.htm"
 "http://www1.hollins.edu/Docs/CompTech/Blackboard/bb_faq.htm"
 "http://www1.hollins.edu/Docs/comptech/comptech.htm"
 "http://www1.hollins.edu/Docs/Academics/international_programs/index.htm"
 "http://www1.hollins.edu/Docs/academics/online/cyber.htm"
 ⋮
 "http://www1.hollins.edu/classes/comm250/valentinesr/FinalProject/head.html"
 "http://www1.hollins.edu/classes/comm250/valentinesr/FinalProject/menu.html"
 "http://www1.hollins.edu/classes/comm250/valentinesr/FinalProject/main.html"
 "http://www1.hollins.edu/Docs/CampusLife/StudentAct

In [138]:
links = df[6013:end,1:2]

23875×2 DataFrame
   Row │ 6012   23875  
       │ Int64  String 
───────┼───────────────
     1 │     1  2
     2 │     8  2
     3 │    16  2
     4 │    18  2
     5 │    20  2
     6 │    23  2
     7 │    26  2
     8 │    27  2
     9 │    28  2
    10 │    29  2
    11 │    30  2
   ⋮   │   ⋮      ⋮
 23866 │  6005  6004
 23867 │  5955  6005
 23868 │  6004  6005
 23869 │  6002  6006
 23870 │  6002  6007
 23871 │  6002  6008
 23872 │  6002  6009
 23873 │  6002  6010
 23874 │  6002  6011
 23875 │  6005  6012
     23854 rows omitted

In [15]:
webpages[links[2,2]]

"http://www1.hollins.edu/docs/comptech/mainviruses.htm"

In [12]:
links[2,2]

"2"

In [19]:
webpages[parse(Int32, links[2,2])]

"http://www.hollins.edu/"

In [29]:
length(links[:,1])

23875

In [30]:
length(webpages)

6012

In [41]:
for i in eachindex(links[:,1])
    print(i,": ")
    print(links[i,1])
    println()
    if i == 3
        break
    end
end

1: 1
2: 8
3: 16


In [146]:
Mdata = PageRank(webpages, links)

Rankings:
1. Website 2, (Pagerank = 0.01988)
      http://www.hollins.edu/
2. Website 37, (Pagerank = 0.00929)
      http://www.hollins.edu/admissions/visit/visit.htm
3. Website 38, (Pagerank = 0.00861)
      http://www.hollins.edu/about/about_tour.htm
4. Website 61, (Pagerank = 0.00807)
      http://www.hollins.edu/htdig/index.html
5. Website 52, (Pagerank = 0.00803)
      http://www.hollins.edu/admissions/info-request/info-request.cfm
6. Website 43, (Pagerank = 0.00716)
      http://www.hollins.edu/admissions/apply/apply.htm
7. Website 425, (Pagerank = 0.00658)
      http://www.hollins.edu/academics/library/resources/web_linx.htm
8. Website 27, (Pagerank = 0.00599)
      http://www.hollins.edu/admissions/admissions.htm
9. Website 28, (Pagerank = 0.00557)
      http://www.hollins.edu/academics/academics.htm
10. Website 4023, (Pagerank = 0.00445)
      http://www1.hollins.edu/faculty/saloweyca/clas%20395/Sculpture/sld001.htm


6012×6012 Matrix{Float64}:
 2.49501e-5  2.49501e-5  0.000166334  2.49501e-5  …  0.000166334  0.000166334
 0.0354416   2.49501e-5  0.000166334  2.49501e-5     0.000166334  0.000166334
 0.0354416   2.49501e-5  0.000166334  2.49501e-5     0.000166334  0.000166334
 0.0354416   2.49501e-5  0.000166334  2.49501e-5     0.000166334  0.000166334
 0.0354416   2.49501e-5  0.000166334  2.49501e-5     0.000166334  0.000166334
 0.0354416   2.49501e-5  0.000166334  2.49501e-5  …  0.000166334  0.000166334
 0.0354416   2.49501e-5  0.000166334  0.0354416      0.000166334  0.000166334
 0.0354416   2.49501e-5  0.000166334  2.49501e-5     0.000166334  0.000166334
 0.0354416   2.49501e-5  0.000166334  2.49501e-5     0.000166334  0.000166334
 0.0354416   2.49501e-5  0.000166334  2.49501e-5     0.000166334  0.000166334
 0.0354416   2.49501e-5  0.000166334  2.49501e-5  …  0.000166334  0.000166334
 0.0354416   2.49501e-5  0.000166334  2.49501e-5     0.000166334  0.000166334
 0.0354416   2.49501e-5  0.000166334 

In [23]:
Mdata[1,1]

2.4950099800399207e-5

In [59]:
n = vec(nullspace(Mdata - I))
total = 0
for t in eachindex(n)
    total += n[t]
end
n = n / total

6012-element Vector{Float64}:
 5.805841501884083e-5
 0.01987875063788639
 0.00011256798021877692
 6.011465055054371e-5
 6.01146505505104e-5
 6.011465055055593e-5
 0.0011456412977922542
 0.00011190948769999165
 7.467505808689235e-5
 0.0007221123309062774
 6.0114650550449516e-5
 0.00034689874710901387
 6.236512994764949e-5
 ⋮
 8.934306299668106e-5
 8.934306299668095e-5
 0.00010019186350341473
 0.0003743112242506534
 0.00041563129446014113
 6.890721552525817e-5
 6.890721552525817e-5
 6.890721552525816e-5
 6.890721552525817e-5
 6.890721552525867e-5
 6.890721552525866e-5
 0.00017582061511555892

In [61]:
epsilon = 1
curr = 1/6012 * vec(ones(6012, 1))
while epsilon > 10^-5
    next = Mdata * curr
    epsilon = norm(next - curr)
    curr = next
end
@printf "my number: %.5f" curr[2]

my number: 0.01989

In [38]:
v = 1/6012 * vec(ones(6012, 1))
norm(Mdata * v - v)

0.028869305483107708

In [56]:
using Printf

LoadError: LoadError: MethodError: no method matching var"@printf"(::LineNumberNode, ::Module)
Closest candidates are:
  var"@printf"(::LineNumberNode, ::Module, ::Any, ::Any...) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Printf/src/Printf.jl:867
in expression starting at In[56]:2

printx (generic function with 1 method)